package com.logiair.os.models;

public enum AirWaybillStatus {
    PRE_ALERT,
    AWB_REGISTERED,
    MANIFEST_DECONSOLIDATED,
    CUSTOMS_PRESENTED,
    CUSTOMS_CLEARED,
    MANIFEST_REGISTERED,
    PROCESS_COMPLETED,
    INVOICED
}
